version: '3'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
  database:
    ports:
      - "5432"
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]